volumes:
  org_api_postgres_storage:

networks:
  org_api:

services:
  db:
    image: postgis/postgis:17-3.6-alpine
    ports:
      - "10008:5432"
    env_file:
      - .env
    networks:
      - org_api
    volumes:
      - org_api_postgres_storage:/var/lib/postgresql/data
