volumes:
  org_api_postgres_storage:

networks:
  org_api:

services:
  app:
    build: .
    command: [ "uv", "run", "fastapi", "dev", "main.py", "--host", "0.0.0.0" ]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - path: .env
        required: true
    networks:
      - org_api
  db:
    image: postgis/postgis:17-3.6-alpine
    env_file:
      - .env
    networks:
      - org_api
    volumes:
      - org_api_postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 5
