[project]
name = "org-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.17.0",
    "fastapi[standard]>=0.119.1",
    "geoalchemy2>=0.18.0",
    "psycopg[binary]>=3.2.11",
    "pydantic-settings>=2.11.0",
    "sqlalchemy>=2.0.44",
]
