"""make category.parent_id can be null

Revision ID: dace01cff1d9
Revises: 61670cc3a112
Create Date: 2025-10-22 11:34:21.434044

Doc: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "dace01cff1d9"
down_revision = "61670cc3a112"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("categories", "parent_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("categories", "parent_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
